require('dotenv').config();
const mongoose = require('mongoose');
const Category = require('./models/Category');
const Medicine = require('./models/Medicine');

const MONGO_URI = process.env.MONGO_URI || 'mongodb://mongo-catalog:27017/catalog_db';

const categories = [
  { name: 'Antibiotics', description: 'Fight bacterial infections', icon: 'shield', isActive: true },
  { name: 'Painkillers', description: 'Pain and fever relief', icon: 'thermometer', isActive: true },
  { name: 'Vitamins', description: 'Nutritional supplements', icon: 'sun', isActive: true },
  { name: 'Antidiabetics', description: 'Diabetes management', icon: 'activity', isActive: true },
  { name: 'Antihypertensives', description: 'Blood pressure control', icon: 'heart', isActive: true },
  { name: 'Antacids', description: 'Acidity and stomach relief', icon: 'droplet', isActive: true },
  { name: 'Antihistamines', description: 'Allergy relief', icon: 'wind', isActive: true },
  { name: 'Syrups', description: 'Liquid medicines', icon: 'coffee', isActive: true },
];

const medicines = [
  {
    name: 'Paracetamol 500mg',
    genericName: 'Paracetamol / Acetaminophen',
    manufacturer: 'GSK Pharmaceuticals',
    category: 'Painkillers',
    batchNumber: 'BATCH-PCM-2024',
    expiryDate: new Date('2027-01-01'),
    unitPrice: 25.00,
    unit: 'tablets',
    requiresPrescription: false,
    description: 'Paracetamol 500mg is used for the relief of mild to moderate pain including headache, migraine, nerve pain, toothache, sore throat, period pain and general aches and pains. It is also used to reduce fever.',
    imageUrl: 'https://onemg.gumlet.io/l_watermark_346,w_480,h_480/a_ignore,w_480,h_480,c_fit,q_auto,f_auto/7a74e0a2-8344-4b75-9cf0-5e5cc7d72c8b.jpg',
    isActive: true,
  },
  {
    name: 'Amoxicillin 500mg',
    genericName: 'Amoxicillin Trihydrate',
    manufacturer: 'Sun Pharmaceutical Industries',
    category: 'Antibiotics',
    batchNumber: 'BATCH-AMX-2024',
    expiryDate: new Date('2026-08-01'),
    unitPrice: 85.00,
    unit: 'capsules',
    requiresPrescription: true,
    description: 'Amoxicillin is a penicillin antibiotic used to treat many different types of infection caused by bacteria, such as tonsillitis, bronchitis, pneumonia, and infections of the ear, nose, throat, skin, or urinary tract.',
    imageUrl: 'https://onemg.gumlet.io/l_watermark_346,w_480,h_480/a_ignore,w_480,h_480,c_fit,q_auto,f_auto/2ee37a81-0f84-4b71-8e04-8e748c95adea.jpg',
    isActive: true,
  },
  {
    name: 'Azithromycin 250mg',
    genericName: 'Azithromycin Dihydrate',
    manufacturer: 'Cipla Limited',
    category: 'Antibiotics',
    batchNumber: 'BATCH-AZI-2024',
    expiryDate: new Date('2026-10-15'),
    unitPrice: 120.00,
    unit: 'tablets',
    requiresPrescription: true,
    description: 'Azithromycin is an antibiotic medication used for the treatment of bacterial infections including middle ear infections, strep throat, pneumonia, and certain sexually transmitted infections.',
    imageUrl: '',
    isActive: true,
  },
  {
    name: 'Ibuprofen 400mg',
    genericName: 'Ibuprofen',
    manufacturer: 'Dr Reddys Laboratories',
    category: 'Painkillers',
    batchNumber: 'BATCH-IBU-2024',
    expiryDate: new Date('2026-06-30'),
    unitPrice: 35.00,
    unit: 'tablets',
    requiresPrescription: false,
    description: 'Ibuprofen is a nonsteroidal anti-inflammatory drug used to reduce fever and treat pain or inflammation caused by many conditions such as headache, toothache, back pain, arthritis, menstrual cramps, or minor injury.',
    imageUrl: 'https://onemg.gumlet.io/l_watermark_346,w_480,h_480/a_ignore,w_480,h_480,c_fit,q_auto,f_auto/7a74e0a2-8344-4b75-9cf0-5e5cc7d72c8b.jpg',
    isActive: true,
  },
  {
    name: 'Vitamin C 500mg',
    genericName: 'Ascorbic Acid',
    manufacturer: 'Himalaya Drug Company',
    category: 'Vitamins',
    batchNumber: 'BATCH-VTC-2024',
    expiryDate: new Date('2027-03-01'),
    unitPrice: 45.00,
    unit: 'tablets',
    requiresPrescription: false,
    description: 'Vitamin C is an essential nutrient involved in the repair of tissue and the enzymatic production of certain neurotransmitters. Supports immune system and acts as an antioxidant.',
    imageUrl: '',
    isActive: true,
  },
  {
    name: 'Vitamin D3 1000IU',
    genericName: 'Cholecalciferol',
    manufacturer: 'Abbott India Limited',
    category: 'Vitamins',
    batchNumber: 'BATCH-VTD-2024',
    expiryDate: new Date('2026-12-01'),
    unitPrice: 180.00,
    unit: 'capsules',
    requiresPrescription: false,
    description: 'Vitamin D3 helps your body absorb calcium and phosphorous. Used for the prevention and treatment of vitamin D deficiency and associated diseases like rickets and osteomalacia.',
    imageUrl: '',
    isActive: true,
  },
  {
    name: 'Multivitamin Daily',
    genericName: 'Multivitamin and Minerals',
    manufacturer: 'Pfizer Limited',
    category: 'Vitamins',
    batchNumber: 'BATCH-MTV-2024',
    expiryDate: new Date('2027-06-01'),
    unitPrice: 299.00,
    unit: 'tablets',
    requiresPrescription: false,
    description: 'A comprehensive multivitamin supplement providing essential vitamins and minerals for daily nutrition. Supports overall health, energy levels and immune function.',
    imageUrl: '',
    isActive: true,
  },
  {
    name: 'Metformin 500mg',
    genericName: 'Metformin Hydrochloride',
    manufacturer: 'Sun Pharmaceutical Industries',
    category: 'Antidiabetics',
    batchNumber: 'BATCH-MET-2024',
    expiryDate: new Date('2026-11-01'),
    unitPrice: 28.00,
    unit: 'tablets',
    requiresPrescription: true,
    description: 'Metformin is the first-line medication for the treatment of type 2 diabetes. It decreases glucose production by the liver and improves insulin sensitivity of body tissues.',
    imageUrl: '',
    isActive: true,
  },
  {
    name: 'Glipizide 5mg',
    genericName: 'Glipizide',
    manufacturer: 'Cipla Limited',
    category: 'Antidiabetics',
    batchNumber: 'BATCH-GLP-2024',
    expiryDate: new Date('2026-07-15'),
    unitPrice: 42.00,
    unit: 'tablets',
    requiresPrescription: true,
    description: 'Glipizide is an oral diabetes medicine that helps control blood sugar levels. It works by stimulating the release of insulin from the pancreas.',
    imageUrl: '',
    isActive: true,
  },
  {
    name: 'Amlodipine 5mg',
    genericName: 'Amlodipine Besylate',
    manufacturer: 'Dr Reddys Laboratories',
    category: 'Antihypertensives',
    batchNumber: 'BATCH-AML-2024',
    expiryDate: new Date('2027-02-01'),
    unitPrice: 55.00,
    unit: 'tablets',
    requiresPrescription: true,
    description: 'Amlodipine is a calcium channel blocker used to treat high blood pressure and chest pain. Lowering high blood pressure helps prevent strokes, heart attacks, and kidney problems.',
    imageUrl: '',
    isActive: true,
  },
  {
    name: 'Atenolol 50mg',
    genericName: 'Atenolol',
    manufacturer: 'GSK Pharmaceuticals',
    category: 'Antihypertensives',
    batchNumber: 'BATCH-ATN-2024',
    expiryDate: new Date('2026-05-01'),
    unitPrice: 38.00,
    unit: 'tablets',
    requiresPrescription: true,
    description: 'Atenolol is a beta-blocker used in the management of hypertension, angina, and certain heart rhythm disorders. It works by slowing the heart rate and relaxing blood vessels.',
    imageUrl: '',
    isActive: true,
  },
  {
    name: 'Omeprazole 20mg',
    genericName: 'Omeprazole',
    manufacturer: 'Cipla Limited',
    category: 'Antacids',
    batchNumber: 'BATCH-OMP-2024',
    expiryDate: new Date('2026-08-15'),
    unitPrice: 65.00,
    unit: 'capsules',
    requiresPrescription: false,
    description: 'Omeprazole reduces the amount of acid your stomach produces. It is used to treat acid reflux, peptic ulcer disease, Zollinger-Ellison syndrome, and gastroesophageal reflux disease.',
    imageUrl: '',
    isActive: true,
  },
  {
    name: 'Pantoprazole 40mg',
    genericName: 'Pantoprazole Sodium',
    manufacturer: 'Sun Pharmaceutical Industries',
    category: 'Antacids',
    batchNumber: 'BATCH-PAN-2024',
    expiryDate: new Date('2027-01-15'),
    unitPrice: 75.00,
    unit: 'tablets',
    requiresPrescription: false,
    description: 'Pantoprazole is a proton pump inhibitor that decreases the amount of acid produced in the stomach. Used for treatment of gastroesophageal reflux disease and Zollinger-Ellison syndrome.',
    imageUrl: '',
    isActive: true,
  },
  {
    name: 'Cetirizine 10mg',
    genericName: 'Cetirizine Hydrochloride',
    manufacturer: 'Abbott India Limited',
    category: 'Antihistamines',
    batchNumber: 'BATCH-CTZ-2024',
    expiryDate: new Date('2026-09-01'),
    unitPrice: 22.00,
    unit: 'tablets',
    requiresPrescription: false,
    description: 'Cetirizine is an antihistamine used to relieve allergy symptoms such as watery eyes, runny nose, itching eyes and nose, sneezing, hives, and itching. It works by blocking histamine.',
    imageUrl: '',
    isActive: true,
  },
  {
    name: 'Loratadine 10mg',
    genericName: 'Loratadine',
    manufacturer: 'Novartis India Limited',
    category: 'Antihistamines',
    batchNumber: 'BATCH-LOR-2024',
    expiryDate: new Date('2026-11-30'),
    unitPrice: 30.00,
    unit: 'tablets',
    requiresPrescription: false,
    description: 'Loratadine is a non-drowsy antihistamine that provides relief from symptoms of hay fever and allergic rhinitis, including sneezing, runny nose, and itchy red watery eyes.',
    imageUrl: '',
    isActive: true,
  },
  {
    name: 'Cough Syrup 100ml',
    genericName: 'Dextromethorphan HBr',
    manufacturer: 'Himalaya Drug Company',
    category: 'Syrups',
    batchNumber: 'BATCH-CSY-2024',
    expiryDate: new Date('2026-10-01'),
    unitPrice: 110.00,
    unit: 'ml',
    requiresPrescription: false,
    description: 'A sugar-free cough syrup that provides relief from dry, irritating cough. Contains dextromethorphan which acts on the cough centre in the brain to suppress the urge to cough.',
    imageUrl: '',
    isActive: true,
  },
  {
    name: 'Antacid Suspension 170ml',
    genericName: 'Aluminium Hydroxide + Magnesium Hydroxide',
    manufacturer: 'Pfizer Limited',
    category: 'Antacids',
    batchNumber: 'BATCH-ASY-2024',
    expiryDate: new Date('2026-07-01'),
    unitPrice: 85.00,
    unit: 'ml',
    requiresPrescription: false,
    description: 'Antacid suspension provides rapid relief from acidity and heartburn. It works by neutralizing excess stomach acid. Suitable for hyperacidity, gastric ulcer, and gastroesophageal reflux.',
    imageUrl: '',
    isActive: true,
  },
  {
    name: 'Ciprofloxacin 500mg',
    genericName: 'Ciprofloxacin Hydrochloride',
    manufacturer: 'Cipla Limited',
    category: 'Antibiotics',
    batchNumber: 'BATCH-CIP-2024',
    expiryDate: new Date('2026-04-30'),
    unitPrice: 95.00,
    unit: 'tablets',
    requiresPrescription: true,
    description: 'Ciprofloxacin is a fluoroquinolone antibiotic used to treat a number of bacterial infections including bone and joint infections, intra-abdominal infections, infectious diarrhea, and urinary tract infections.',
    imageUrl: '',
    isActive: true,
  },
  {
    name: 'Aspirin 75mg',
    genericName: 'Acetylsalicylic Acid',
    manufacturer: 'Bayer Pharmaceuticals',
    category: 'Painkillers',
    batchNumber: 'BATCH-ASP-2024',
    expiryDate: new Date('2027-04-01'),
    unitPrice: 18.00,
    unit: 'tablets',
    requiresPrescription: false,
    description: 'Low-dose aspirin used for prevention of blood clots, heart attacks and strokes. Also used as a pain reliever and fever reducer. Works by inhibiting prostaglandin synthesis.',
    imageUrl: '',
    isActive: true,
  },
  {
    name: 'Diclofenac 50mg',
    genericName: 'Diclofenac Sodium',
    manufacturer: 'Novartis India Limited',
    category: 'Painkillers',
    batchNumber: 'BATCH-DCF-2024',
    expiryDate: new Date('2026-09-20'),
    unitPrice: 42.00,
    unit: 'tablets',
    requiresPrescription: true,
    description: 'Diclofenac is a nonsteroidal anti-inflammatory drug used to treat pain and inflammatory conditions such as arthritis, ankylosing spondylitis, and menstrual cramps.',
    imageUrl: '',
    isActive: true,
  },
];

const seed = async () => {
  try {
    await mongoose.connect(MONGO_URI);
    console.log('[catalog-service] Connected to catalog_db');

    await Category.deleteMany({});
    await Medicine.deleteMany({});
    console.log('[catalog-service] Cleared existing catalog data');

    const insertedCategories = await Category.insertMany(categories);
    console.log('[catalog-service] Inserted ' + insertedCategories.length + ' categories');

    const insertedMedicines = await Medicine.insertMany(medicines);
    console.log('[catalog-service] Inserted ' + insertedMedicines.length + ' medicines');

    console.log('[catalog-service] Catalog seed completed successfully');
    process.exit(0);
  } catch (err) {
    console.error('[catalog-service] Seed failed:', err.message);
    process.exit(1);
  }
};

seed();
